services:
  - type: web
    name: attrisight
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn attrition.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "attrisight-2.onrender.com"

